### ISSUE TITLE
transfer - crossChain update

### ISSUE THREAD

**Issue by RomeroYang** [polkawallet-io/app#102]
make destination address editing an advanced option

**Comment by RomeroYang** [comment]
![image](https://user-images.githubusercontent.com/10572804/148046257-9015199b-4be8-4d9f-b908-be08d24d7589.png)

**Comment by MarchAlice** [comment]
> make destination address editing an advanced option
![page_1](https://user-images.githubusercontent.com/93580414/148192718-ff8489e9-69cc-44dc-8821-01ea661ad069.png)
1. add check box below the destination address box
2. users can not edit the destination address without ticking the check box
3. when the check box has been ticked, show the warning description, and meanwhile, users can edit the destination address.
