### ISSUE TITLE
claim rewards amount under ED

### ISSUE THREAD

**Issue by RomeroYang** [polkawallet-io/app#178]
add tip for tiny rewards claim

https://github.com/AcalaNetwork/polkawallet_plugin_karura/commit/8d3cd0dee72aed98677c61953b2e8a1ddb2dffd4

https://github.com/AcalaNetwork/polkawallet_plugin_acala/commit/ab6632852a5fa51c05db59e40524983b30904979

**Comment by MarchAlice** [comment]
Add tip under the claim button
Content:
The Claims may fail due to 0.0582771104 ACA is required as ED
