### ISSUE TITLE
ChainX Plugin Request

### ISSUE THREAD

**Issue by true-eye** [polkawallet-io/app#23]
**Para-chain name**
ChainX

**Description**
Overview of your para-chain.
 - Website: https://chainx.org
 - Application: https://dapps.chainx.org/
 - Plugin repo: https://github.com/true-eye/polkawallet_plugin_chainx
 - Hash: 225f62ae68adfef0d50bdb4d2eb6a34e4f518269

**Plugin functions**
Overview of your Plugin.
 - My Stake
 - Staking Overview (Validators, Candidates, Dropouts) with vote functionality
 - Governance (Similar functionality like Polkadot or Kusama, just except Polkassembly)

**Comment by RomeroYang** [comment]
We want to use a new version of `polkawallet-io/sdk` in next release, but the new one is not published yet.

So you may need to use the `develop` branch of `polkawallet-io/sdk` and `polkawallet-io/polkawallet_plugin_kusama`, do some modification and wait for a new `polkawallet-io/sdk` release in [pub.dev](https://pub.dev/).

**Comment by true-eye** [comment]
@RomeroYang Thank you for letting me know. 
When will the new version of SDK be released?
And is the `develop` branch of polkawallet_plugin_kusama mainly updated?

**Comment by RomeroYang** [comment]
> @RomeroYang Thank you for letting me know.
> When will the new version of SDK be released?
> And is the `develop` branch of polkawallet_plugin_kusama mainly updated? Or should I also wait for that?

It will be released in this week. You may wait for the `master` branch update.

**Comment by YuQiYang** [comment]
> @RomeroYang Thank you for letting me know.
> When will the new version of SDK be released?
> And is the `develop` branch of polkawallet_plugin_kusama mainly updated? Or should I also wait for that?

noticed that SDK had update, please  continue ChainX plugin

**Comment by RomeroYang** [comment]
> > @RomeroYang Thank you for letting me know.
> > When will the new version of SDK be released?
> > And is the `develop` branch of polkawallet_plugin_kusama mainly updated? Or should I also wait for that?
> 
> noticed that SDK had update, please continue ChainX plugin

The new SDK will be released this week, ChainX plugin may be in next week.

**Comment by RomeroYang** [comment]
New SDK was released: https://pub.dev/packages/polkawallet_sdk

**Comment by true-eye** [comment]
Yes. I will update them as soon as possible.

**Comment by true-eye** [comment]
@RomeroYang I've updated the (1).
Not sure what I should do for (2) & (3). Is there any plugin (polkawallet_plugin_kusama or polkawallet_plugin_acala) that I can see the example updates?
Thanks

**Comment by RomeroYang** [comment]
see: https://github.com/polkawallet-io/sdk/commit/2cc14c76f402a4cd8d2ba7b0b74527645600e71a

1. create chainX `metadata.ts` in `js_service_chainx/src/constants/` like `js_api/src/constants/networkMetadata.ts`
2. update `signAsync()` function in `js_service_chainx/src/service/keyring.ts`.

**Comment by true-eye** [comment]
Thanks, I've updated!
By the way, what should be the metadata string for ChainX?

**Comment by RomeroYang** [comment]
A easy way to get the metadata of a substrate-based chain is:
1. open a web page which can connect to a node through `ws/wss` in Chrome.
2. open the Devtool, go to `Network` panel, and find the `ws` connection.
3. you'll find the result of a `state_getMetadata` request, that's the string you need.
![image](https://user-images.githubusercontent.com/10572804/110726002-9219e880-8253-11eb-8b1d-ad8cf5586934.png)

**Comment by true-eye** [comment]
cool man! Thanks. I will

**Comment by true-eye** [comment]
Done!

**Comment by RomeroYang** [comment]
> Done!

Could you paste a plugin repo commit hash here? so I can use a specific version of your plugin.

And you also need to submit a commit hash here if your plugin has a updated version in the future.

**Comment by true-eye** [comment]
Sure!
959a35d4480a635d6245f7429be9b1b02a45db9c

**Comment by RomeroYang** [comment]
Some issues in the code you need to update:
1. use flutter_svg: ^0.19.3 in `pubspec.yaml`.
2. update type of `tokenSymbol` and `tokenDecimals` to `List`, see #24 .

The latest `polkadot-js/apps` staking page shows the `blocks nominations` status of validator, if your plugin need this update, use `sdk: ^0.1.2`.

**Comment by true-eye** [comment]
Thanks for the guide!
Updated. the flutter_svg, `tokenSymbol` & `tokenDecimals`.
For blocks nomination, it doesn't need for ChainX.

Hash: 39573cfbf005e061ca31b3b884b2bc428a622930

**Comment by RomeroYang** [comment]
I just add your plugin in the App in dev, find some image files need update.
1. `chainx_gray.png` should be a shap in gray, and the color is `#9e9e9e`. It should have a little padding, because it looks a bit big now:
![image](https://user-images.githubusercontent.com/10572804/110902434-dafb9b00-8340-11eb-84da-3b72d495507f.png)

2. `bg.png` should have a transparent background color, it will display as texture on a block with themeColor, like below:
![image](https://user-images.githubusercontent.com/10572804/110901484-58bea700-833f-11eb-8b4f-88c44148c65b.png)

but chainX has a bright yellow theme color, so I think your `bg.png` should have a dark background, like this:
![image](https://user-images.githubusercontent.com/10572804/110901722-b7842080-833f-11eb-8103-632a150c5f6b.png)

now it looks like this in the app:
![image](https://user-images.githubusercontent.com/10572804/110902554-0bdbd000-8341-11eb-8d0c-8066e52a41f3.png)


3. you'd better delete the unused assets like `polkadot.png`, `staking_pink.png` for reducing the package size.

**Comment by RomeroYang** [comment]
Unhandled Exception: type 'String' is not a subtype of type 'int' for `ValidatorData.registeredAt`

![image](https://user-images.githubusercontent.com/10572804/110904251-a3dab900-8343-11eb-9403-e90204cc62fc.png)

And there's a WARNING in your ts file: 
```
I/chromium(13723): [INFO:CONSOLE(33)] "@polkadot/types-known has multiple versions, ensure that there is only one installed.
I/chromium(13723): Either remove and explicitly install matching versions or deupe using your package manager.
I/chromium(13723): The following conflicting packages were found:
I/chromium(13723): 	3.11.1	<unknown>
I/chromium(13723): 	3.11.1	<unknown>", source:  (33)
```

you can test your `js_service_chainx` code through opening `js_service_chainx/test/index.html` in chrome.

**Comment by Exxibition** [comment]
> 1. `chainx_gray.png` should be a shap in gray, and the color is `#9e9e9e`. It should have a little padding, because it looks a bit big now:

I noticed the gray version of the DOT icon has 2 gray tones. I assume I can simply make a lighter version of the current icon but with different shades. All based off `#9e9e9e` of course.


> 2. `staking.png` and `governance.png` were replaced with `svg` images, see develop branch of `polkawallet_plugin_kusama`.

Am I looking at the correct pictures of a hand for staking and the 'voting ballot' for governance?

**Comment by Exxibition** [comment]
As for the bg.png, shouldn't that be more of an effect on yellow then? Like Polkadot? I'd much rather go along with the theme colour with an effect over it, than stick out from the app's design choices and make a dark background with yellow accents

**Comment by true-eye** [comment]
@RomeroYang Fixed all the issues you mentioned. But not sure why ValidatorData is not working on new release. Is there any data conversion? I would like to test on my side but I think the `app` and other plugins are not updated on github as master.. So can't setup on local. However, I've fixed so please check again. 

Thanks!

ced17371c4b35f8ea97c155bec102caa5af39e54

**Comment by Exxibition** [comment]
@RomeroYang Do you have an update for us regarding the above?

**Comment by RomeroYang** [comment]
> @RomeroYang Do you have an update for us regarding the above?

Working on Acala TC6 upgrade now, I will look into it next week.

**Comment by true-eye** [comment]
Hi, @RomeroYang 
I hope you are doing well. Just greetings. :)

**Comment by Exxibition** [comment]
Hey @RomeroYang Sorry to press you again. Could you give us a little update on the timeline, anything we can do to help out?

**Comment by RomeroYang** [comment]
`Polkawallet SDK` updated to `v0.1.4` now, you need to update `signTxAsExtension` and `signBytesAsExtension` in `js_service_chainx/src/service/keyring.ts`, see https://github.com/polkawallet-io/sdk/commit/d43e7d5ad98ac88c8f3e77d8e246f5d9ba1c9ccd.

**Comment by RomeroYang** [comment]
We have a polkawallet_ui package update today, see https://github.com/polkawallet-io/app/issues/24#issuecomment-810791482

**Comment by RomeroYang** [comment]
Waitting for your update @true-eye

**Comment by true-eye** [comment]
yup. I am updating now

**Comment by true-eye** [comment]
@RomeroYang I've updated polkawallet_ui git ref and signTxAsExtension/signBytesAsExtension. please check

**Comment by true-eye** [comment]
@RomeroYang I've found some interface mismatch after upgrading the app. I need to fix them. I will let you know once fix

**Comment by true-eye** [comment]
@RomeroYang Finally, fixed all issues. Please check. Thanks

**Comment by true-eye** [comment]
@RomeroYang Added bunch of staking functionalities (vote, rebond, claim, unbond, refresh)
The new hash: 07b601d0aaae0b173e7a18006f7502b9bb55b32d
Please update, Thanks

**Comment by true-eye** [comment]
@RomeroYang How are you doing? When will we launch the new release?

**Comment by RomeroYang** [comment]
> @RomeroYang How are you doing? When will we launch the new release?

Working on new features, this may take several days.

**Comment by true-eye** [comment]
@RomeroYang I hope you are doing well.

The ChainX plugin has been updated with the following
- unfreeze feature
- unbound issue fixed
- use custom identity module

the new hash: 225f62ae68adfef0d50bdb4d2eb6a34e4f518269
Please update, thanks

**Comment by true-eye** [comment]
@RomeroYang When will we release the next version? any hope this month?

**Comment by RomeroYang** [comment]
We will have `sdk v0.1.6` in next version, preview of the update here: https://github.com/polkawallet-io/polkawallet_plugin_laminar/commit/6da394e330376f84dc973b7be716765d682144c7

**Comment by true-eye** [comment]
What should I do for this update?

**Comment by true-eye** [comment]
Could we release the minor version with chainx update before the sdk update, please?

**Comment by RomeroYang** [comment]
will do, we have a release this week with this update https://github.com/polkawallet-io/app/commit/7f30c707c17366270bbba0e66b504b644acfc65e

**Comment by RomeroYang** [comment]
> What should I do for this update?

you should update the `genesisHash` string like this: https://github.com/polkawallet-io/polkawallet_plugin_laminar/commit/6da394e330376f84dc973b7be716765d682144c7

the one in `networkSpect.ts` file is for off-line-signature, and the one in `plugin.dart` file is for network check while sending tx.
you can get the genesisHash through `api.genesisHash.toString()` in js env.

**Comment by true-eye** [comment]
I've updated the sdk version to `0.1.6`.
- added `genesisHash`.
- For networkSpec.ts file, added CHAINX (genesisHash, SubstrateNetworkKeys)

0.1.6 hash: `0692cbb02da9cfd59eae2856e6e2819c072d4cd3`

**Comment by true-eye** [comment]
> will do, we have a release this week with this update [7f30c70](https://github.com/polkawallet-io/app/commit/7f30c707c17366270bbba0e66b504b644acfc65e)

@RomeroYang Did we launch this?

**Comment by true-eye** [comment]
@RomeroYang I think, the new version was only released on IOS. Any plan to release on Android?

**Comment by RomeroYang** [comment]
New sdk 1.0.8 released! Check the changes in latest commits of branch develop of `polkawallet_plugin_kusama`.

**Comment by RomeroYang** [comment]
The App is ready for new release, please update to polkawallet_sdk 1.0.8+ and submit as soon as possible.

**Comment by Exxibition** [comment]
Sorry RomeroYang I have two questions:

1. Do you mean this one? https://github.com/polkawallet-io/polkawallet_plugin_kusama/commit/66fd0e59fcb54206590ebcec4ce34a41dffe5132

2. Is there a chance that we could hire the PolkaWallet team to include updates from your side in our plugin? (i.e. only when we want to add functionality to chainx directly, we can do so, but other maintenance etc would be done by you, like this SDK update) 

I'd be more than happy to discuss, please let me know in Telegram t.me/Exxibition

**Comment by Exxibition** [comment]
@RomeroYang Please see my latest message in Telegram

**Comment by Exxibition** [comment]
Hi Romero,

The team has built an updated version here: https://github.com/chainx-org/polkawallet_plugin_chainx

I believe they contacted you on the matter, but I just wanted to make sure 😊 


Let me know the progress please and whether we need to amend anything.

**Comment by RomeroYang** [comment]
@Exxibition The new plugin is not functioning, I have notified the developer to fix it last week.

**Comment by Exxibition** [comment]
I heard yesterday. Thank you Romero!
