### ISSUE TITLE
Send All of funds

### ISSUE THREAD

**Issue by amirhosein707** [polkawallet-io/app#28]
Hello how to send your entire balance out your account?
Thank you

**Comment by RomeroYang** [comment]
I don't think it's possible to send out all your balance. If you have experience of using BTC or ETH or any crypto currency, you will know that an account always need some tokens left for paying transaction fees.

**Comment by amirhosein707** [comment]
> I don't think it's possible to send out all your balance. If you have experience of using BTC or ETH or any crypto currency, you will know that an account always need some tokens left for paying transaction fees.

I mean ONE DOT activation cost which is a high cost considering the price of DOT token. Tokens can be completely withdrawn in polkadot.js wallet, is this not possible in Polkawallet?

**Comment by RomeroYang** [comment]
Any transaction you can do with polkadot.js Chrome extension are supported in Polkawallet. You can describe your issue and upload some screenshot if you find bugs in the App.

**Comment by amirhosein707** [comment]
> Any transaction you can do with polkadot.js Chrome extension are supported in Polkawallet. You can describe your issue and upload some screenshot if you find bugs in the App.

In the image I attached, the keep-alive option is available in polkawallet?

![I7pEmKfSUx1doPbEHKvyg0iS-SZW3LrqYA](https://user-images.githubusercontent.com/81331131/112434922-b3093000-8d61-11eb-8cf8-981712c1a6fb.png)

**Comment by RomeroYang** [comment]
The keep-alive option is available in polkawallet v2.0.0, released yesterday.

And with the keep-alive option keeps the existencial deposit so you can not send out all your balance. The old Polkawallet do not have this option so you can send out most of your balance and kill your account.

**Comment by amirhosein707** [comment]
> The keep-alive option is available in polkawallet v2.0.0, released yesterday.
> 
> And the keep-alive option keeps the existencial deposit so you can not send out all your balance. The old Polkawallet do not have this option so you can send out most of your balance and kill your account.

Thank you very much my problem was solved.
