### ISSUE TITLE
Cannot import account from keystore

### ISSUE THREAD

**Issue by Exxibition** [polkawallet-io/app#29]
**Describe the bug**
Unsure of how to actually restore from Keystore.json. I can't figure out a way to actually select the file and import it into the wallet.

**To Reproduce**
1. Go to Select wallet
2. Click on Add account
4. See inability to select the keystore file saved on the device

**Expected behavior**
Perhaps a 'file storage' permission to pop up, after which permission can be given to select a file from your device, and then select the keystore.json file exported from the polkadot.js.org/extension

**Screenshots**
Video instead: 

https://user-images.githubusercontent.com/66322681/113568470-e9239b00-9610-11eb-99dd-4a9e9ae1cdc8.mp4

**Smartphone (please complete the following information):**
 - Device: Oneplus 6 - but I believe this to be non-essential
 - OS: OxygenOS version 10.3.9
 - Version v2.0.2-beta.2

**Additional context**
N/a

**Comment by RomeroYang** [comment]
.json files are plain text files, you can open your keystore.json file with a text editor on your PC, and copy&paste the content into the App.

The wallet App doesn't support selecting files because IOS do not allow reading files from device.

**Comment by Exxibition** [comment]
Ok that makes a whole lot of sense all of a sudden haha!

Thank you for your prompt response and inclusion of ChainX in the mobile wallet 👍
