### ISSUE TITLE
Character limit for passwords

### ISSUE THREAD

**Issue by Exxibition** [polkawallet-io/app#31]
**Is your feature request related to a problem? Please describe.**
User reported a limit of 18 characters in the password for a wallet. 

**Describe the solution you'd like**
Is there a particular reason this limit exists, or could this be increased?

**Additional context**
![IMG_20210409_131451_662](https://user-images.githubusercontent.com/66322681/114172598-256b3a00-9936-11eb-9fbe-a3f4fe84d58f.jpg)

**Comment by RomeroYang** [comment]
Polkawallet encrypted and stored users‘ mnemonic locally with the password. To encrypt, we use a dart package which requires a 32 digits length hex string as a private key. Now we convert the password string to a 32 hex string like this: https://github.com/polkawallet-io/sdk/blob/d43e7d5ad98ac88c8f3e77d8e246f5d9ba1c9ccd/lib/utils/index.dart#L6.

That means, if the password string length is more than 15, the tail will be dropped for encrypting. password A `000000000000000`(15 digits), password B `000000000000000b`(16 digits), password C `000000000000000cde`(18 digits) will be converted to a same private key of password A.

We may update the code and fix this issue in the future, but for now, a password more than 15 digits will not bring you more safety than a 15 digits one.

**Comment by RomeroYang** [comment]
But I think we can increase the input limit, how many do you think is suitable for common users? 24 may be better?

**Comment by Exxibition** [comment]
I asked the user who originally asked (Guy works in security and kind of just wants to be able to haha) thinks 28 to 32 should be enough. 

If you can make this work that'd be amazing. 🤗

**Comment by RomeroYang** [comment]
> I asked the user who originally asked (Guy works in security and kind of just wants to be able to haha) thinks 28 to 32 should be enough.
> 
> If you can make this work that'd be amazing. 🤗

we will make it 32.
