### ISSUE TITLE
Missing Observation Wallet Option

### ISSUE THREAD

**Issue by ajcrowe** [polkawallet-io/app#35]
**Describe the bug**

After install of the wallet on android the observation wallet option is missing

**To Reproduce**
1. Open app
2. tap "Import Account"
3. tap "Source Type"
4. See missing "Observation" account option

**Expected behavior**

Observation account option is available for selection

**Screenshots**

![Screenshot_20210422-144043](https://user-images.githubusercontent.com/1078691/115724397-d3380900-a378-11eb-9f10-8a443aabb9db.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 11
 - Version 2.0.3

**Comment by RomeroYang** [comment]
This option in `Import Account` page is misleading for new users, the wallet didn't have the private key of the observation account, so we removed the option from this page.

You can go to `profile -> address book` and create a contact address, and set it observation, then you get an observation account.

**Comment by ajcrowe** [comment]
But how do you get to that from the initial starting screen? 

Do I have to create a wallet I don't want to use first?

**Comment by RomeroYang** [comment]
I'm afraid you have to create one first.

We have to remove that option due to some users reported assets lost by misunderstanding what a `observation account` is.

**Comment by ajcrowe** [comment]
Gotcha, seems a shame as it's the most secure way to use the wallet

Thanks for the reply 👍
