### ISSUE TITLE
CANNOT unstake KSM from Polkawallet !! Kindly assist, SVP!

### ISSUE THREAD

**Issue by MikeMcGannon** [polkawallet-io/app#41]
Hello!
**Describe the bug**
A clear and concise description of what the bug is: 2 related issues/bugs:
1) Despite staking my KSM weeks ago (13 May 21), I have NEVER received ANY rewards at all; (see attached screenshot).

2) In anticipation of the KSM/KUR parachain auction, I tried tp UNBOND but the app did not allow (see attached screenshot). 

The KSM seem to be stuck in the bonding. The 'Unbonding' button stays unlit, while 'Bond More' is the only lit (i.e., available) option.

I expected the KSM to unstake!!

**Screenshots**
![K Wallet ](https://user-images.githubusercontent.com/75240024/121344293-835ad480-c91b-11eb-92aa-cef1a159bf70.jpg)

**Smartphone (please complete the following information):**
 - Devise/Phone = Samsung A10s
 - OS = One UI 2.0
 - Version = Android 9.0 (Pie), upgradable to Android 10, 
 - 
**Additional context** Add any other context about the problem here.
Unbonding used to work, no more!

Thank you!
Dr Mike

**Comment by RomeroYang** [comment]
unbund token is a controller account action，the button will be available if you switch to your controller account.

**Comment by MikeMcGannon** [comment]
worked thanks!!
