### ISSUE TITLE
Cannot connect to Kusama wallet 

### ISSUE THREAD

**Issue by sraske** [polkawallet-io/app#42]
**Describe the Bug**
I cannot connect to and use my Kusama wallet on Polkawallet

**To Reproduce**
1. Go to Kusama wallet 
2. It attempts to connect to remote node
3. Nothing happens 

**Expected behavior**
I am able to connect to my Polkadot account but not Kusama, I cannot access my funds 

**Screenshots**
None 

**Smartphone (please complete the following information):**
 - Device:iPhone8
 - OS: iOS14.6
 

**Additional context**

**Comment by sraske** [comment]
Wallet version is 2.0.8-beta v2

**Comment by RomeroYang** [comment]
this issue is caused by kusama node update https://github.com/paritytech/polkadot/releases/tag/v0.9.5, the latest release 2.0.9 has fixed it.
