### ISSUE TITLE
Cannot connect to Kusama wallet

### ISSUE THREAD

**Issue by MaviXtrader** [polkawallet-io/app#43]
**Describe the bug**
I can’t connect to kusama wallet on polkawallet

**To Reproduce**
1. Go to Kusama wallet
2. It attempts to connect to remote node
3. Nothing happens

**Expected behavior**
I am able to see my funds in the wallet

**Screenshots**

![image](https://user-images.githubusercontent.com/86320946/122981695-a8116c00-d35f-11eb-8836-16cbf4d49502.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 8plus
 - OS: iOS 14.6
 

**Additional context**
none

**Comment by RomeroYang** [comment]
duplicated with #42
