### ISSUE TITLE
Urgent  my account and investment loss. 

### ISSUE THREAD

**Issue by dursunal** [polkawallet-io/app#44]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [e.g. 0.9.1-beta.1]

**Additional context**
I connected to my polkawallet dot and ksm account with my iphone with a mac address of (I sent to acala support).   You can see from the beer to the bag holder.  I have previously informed you that I could not reach my wallet.  My wallet that I can't reach is Ea9YVo9Nw4khz96WvLjhGAAxLGFYuzJr8K3pd3rdtaDPcef

. My account is not visible in my polkawallet Wallet.  Therefore, I can't see my karura balance either.  I can't add the ksm wallet where I bought Karura tokens.  I am sending the attached images of the wallets that appear in my polkawallet account.  I don't want to lose my money. | The vollet adress I have mentioned below. My account is not visible in my polkawallet Wallet.  Therefore, I can't see my karura balance either.  I can't add the ksm wallet where I bought Karura tokens.  I am sending the attached images of the wallets that appear in my polkawallet account.  I don't want to lose my money.
-- | --
The vollet adress I have mentioned below. My account is not visible in my polkawallet Wallet.  Therefore, I can't see my karura balance either.  I can't add the ksm wallet where I bought Karura tokens.  I am sending the attached images of the wallets that appear in my polkawallet account.  I don't want to lose my money.

I sign in mnomenic or raw seed. But my ksm and dot dont import my polkawallet. I sent you all information and screenshot that wallet mine. Please can you send me information or link for sign in or recover to my wallet? 

I sent to Acala all screenshots and informations. But l can not get helps. 

I don't even want to think that you won't be able to help from a big company like you.  You need to add a way to retrieve code and information such as mobile phone, e-mail address to the system.  I have sent my entire investment to you.  I will send you whatever information you want.  identity information, pictures, videos, etc.  I proved that I sent you ksm from my Binance account with screenshots.  I don't want to regret trusting polkawallet and ksm. 

I am a lawyer.  I don't want to open your first case.  It is the best option for you to understand me and give me my due.

I'm waiting for a solution not a suggestion please. 

I tried all the options to fix the problem.  I even restored my phone.  but there are no mnomenics other than the ones I have.  

My name is Dursun AL. My mail address: dursunal@gmail.com

**Comment by dursunal** [comment]
![056221C0-6778-44BC-8DD1-CC9D57BF942A](https://user-images.githubusercontent.com/86559160/123552634-b1e00880-d77f-11eb-9238-79c9f821db35.png)
![C039CF1E-D963-4959-B006-782A1AA02001](https://user-images.githubusercontent.com/86559160/123552636-b3113580-d77f-11eb-99c5-118461f06f0e.png)

When I import my raw seed or mnomenic words I ser this accounts.

**Comment by RomeroYang** [comment]
1. No one can reach a specific account without its original mnemonic or seed.
2. To see the assets of an unreachable account, use [observation account] #35 .
3. Other useful infomaiton, see #33 .

User can only get a set of mnemonic while creating account, I'm curious how can you have a raw seed of your account?

**Comment by dursunal** [comment]
I am so sad for one week. I lossed my account when updated polkawallet. Before update app durimg one day I am not reached account. I am helpless now. I have nothing to say to you. 

Dursun AL
Avukat/ Arabulucu/ LL.M.
