### ISSUE TITLE
Social Recovery is missing in the Profile

### ISSUE THREAD

**Issue by mstcvkr** [polkawallet-io/app#47]
**Describe the bug**
Social Recovery does not exist in the app, this is the post explains the process

https://polkawallet.medium.com/the-guidance-of-social-recovery-in-polkawallet-4dea03e8b07b

**To Reproduce**
1. Download the latest version of the app and check
2. Add account
3. Go to Profile and will see no Social Recovery Exists in the app anymore

**Expected behavior**
here is where it was supposed to be :  

![image](https://user-images.githubusercontent.com/18646349/126045975-16c2ff65-70ae-4d26-ad63-4d5bc2b9923b.png)

**Smartphone (please complete the following information):**

![image](https://user-images.githubusercontent.com/18646349/126046026-d26db4fd-ea0f-46c8-9550-d4ccd83ba4c7.png)

**Comment by RomeroYang** [comment]
Social Recovery is an on-chain function of Kusama network, you need to switch to Kusama to see the entrance.
