### ISSUE TITLE
Issue in loading balance after deposit or withdrawa

### ISSUE THREAD

**Issue by Harsh4760** [polkawallet-io/app#50]
It takes soo much time in refreshing the balance of Dot token at the home page although the transaction showing but balance not getting uodated
 As here we can see ... Balance in blockchain showing 157 but not in the app ...it lags a lot although after clear all cache and restarted app and phone but still an issue.
![Screenshot_20210724-233600__01](https://user-images.githubusercontent.com/50778665/126877689-b1bb7c68-9868-4802-8ac4-6054b52cda51.jpg)
![Screenshot_20210724-232451__01](https://user-images.githubusercontent.com/50778665/126877693-add111ae-defb-4760-a52c-a86106d110e8.jpg)
![Screenshot_20210724-232451__01](https://user-images.githubusercontent.com/50778665/126877694-6ce1242f-8fa1-4663-b38a-1faa914ebabd.jpg)

7(balance) + 88.29+44.95+16.88 = 157 ++ here the last transaction of 16.88 not getting update since too long...

**Comment by RomeroYang** [comment]
Thanks for your feedback, we'll look into the network delay issue.
