### ISSUE TITLE
polkawallet.apk

### ISSUE THREAD

**Issue by ldongting002** [polkawallet-io/app#54]
**Describe the bug**
最新版本2.3.1不能在oppo手机上安装，页面显示有病毒

> 
![654609b7a45d7e09011f226d2abcea6](https://user-images.githubusercontent.com/89511510/131786711-ad68848f-72ca-4fa7-8663-de0ddf0bdf56.jpg)

> 

> 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Apk: [e.g. Apk]
 - Version [e.g. 2.3.1-beta.1]

**Additional context**

**Comment by RomeroYang** [comment]
apk 安装文件现已替换成不包含 bifrost 插件的版本，该版本不会收到安全警告，可以重新下载安装一下。

**Comment by ldongting002** [comment]
应该是哪个版本不带bifrost插件？谢谢

**Comment by RomeroYang** [comment]
> 应该是哪个版本不带bifrost插件？谢谢

版本号还是 2.3.1，现在从官网下载就可以。
