### ISSUE TITLE
对已有的账户导入和新建观察账户

### ISSUE THREAD

**Issue by StrawberryFlavor** [polkawallet-io/app#8]
该账户已经存在的情况下，导入该账户，或建立此账户观察账户
问题描述：
1. 导入并不是覆盖，而是新建了一个
2. 若有此账户，则在建立观察账户时，应不被允许
![image](https://user-images.githubusercontent.com/28721839/100729015-3691c080-3403-11eb-8601-28afe5fe9705.png)

**Comment by RomeroYang** [comment]
1. 修复重复导入，将覆盖原有账户。
2. 建立观察账户允许重复。
