### ISSUE TITLE
展示逻辑优化-

### ISSUE THREAD

**Issue by MarchAlice** [polkawallet-io/app#80]
KAKURA-盈利：
	流动性挖矿中的卡片排序方式，默认为首个卡片为流动性矿池【kar-ksm lp】，其余卡片按照年化收益率（APR）从高到低排序

**Comment by StrawberryFlavor** [comment]
某些情况下APR, 与当前扣除忠诚奖励后的 APR 区别很大。应确定是否采用扣除忠诚奖励后的APR，当前排序采用的为不扣除忠诚奖励的 APR
