### ISSUE TITLE
acala auction fees 

### ISSUE THREAD

**Issue by dani7789** [polkawallet-io/app#90]
Hi
i tried to contribuite 2 times. i had 5 dot in my account. once i finished adding my password said ok but did not pan out and they took me 0.03 dots each time. Did it twice. Then i was able to do it. Why you charged fees when the contribuition was not succeded?

also where i can see my contribuition in the app
thanks

**Comment by StrawberryFlavor** [comment]
You have to reserve enough handling fees to pay for the transaction
