### ISSUE TITLE
Error when i sign in using polkadot js linked to polkawallet 

### ISSUE THREAD

**Issue by chunyeong** [polkawallet-io/app#91]
![855E062B-1F1A-4C64-9B05-EAF5EDD88141](https://user-images.githubusercontent.com/20521490/141336868-f176d7ee-b120-42d3-816e-f24ebe113506.jpeg)

**Comment by StrawberryFlavor** [comment]
What is your offline signing device?

**Comment by chunyeong** [comment]
Iphone 13 pro max with ios 15.1. This error appear when i scan qr code from my pc(chrome)

**Comment by StrawberryFlavor** [comment]
> Iphone 13 pro max with ios 15.1. This error appear when i scan qr code from my pc(chrome)

I think it may be that you are using another network and let polkawallet sign it. What transaction did you make that caused the signature error?

**Comment by chunyeong** [comment]
I try to sign an attestation to verify my account in moonbeam crowdloan using polkadot.js and linked with my polkawallet address…btw it resolved after i import polkawallet address by json

**Comment by StrawberryFlavor** [comment]
> I try to sign an attestation to verify my account in moonbeam crowdloan using polkadot.js and linked with my polkawallet address…btw it resolved after i import polkawallet address by json

Yes, polkawallet does not currently support Moonbeam’s network
