### ISSUE TITLE
Acala parachain

### ISSUE THREAD

**Issue by Vahid57** [polkawallet-io/app#93]
I cant see my dot contribution in acala crowdloans winner tab  in polkawallet

**Comment by Tarzangreg2021** [comment]
I can’t either

**Comment by RomeroYang** [comment]
Only direct contribute can be seen in crowdloan page. Contributions with lcDOT go through an Acala proxy account, so it won't be displayed there. You can check your contributions in Acala's official website https://acala.network/.

**Comment by Vahid57** [comment]
Thanks alot
