### ISSUE TITLE
Crowdloan contribution

### ISSUE THREAD

**Issue by Ninnurta** [polkawallet-io/app#97]
**Describe the bug**
In the crowdloan screen, I contributed to the crowdloan. The transfer is successful but I can not see it in "My Contributions" in the crowdloan page.
Device: Xiaomi Note 9
OS: MIUI 12.5.1

**Comment by RomeroYang** [comment]
Polkawallet may have data reflashing delay as a client, you can confirm the tx on https://www.subscan.io/.

**Comment by Ninnurta** [comment]
> Polkawallet may have data reflashing delay as a client, you can confirm the tx on https://www.subscan.io/.

the contribution was made on 07/Dec/2021. It's been 10 days since; is it normal? The tx seems ok. Result is success... 
I don't know how to use subscan can you help?

**Comment by RomeroYang** [comment]
Go to subscan, search with your address, and you will see all tx history of the address on the page.

The Polkawallet crowdloan page shows my contributions well with my account, you need to wait for the data loading while "My Contributions" shows "--.--".

**Comment by danieldeschamps** [comment]
The same happens too me. I contributed to Acala auction, but the wallet does not display any confiirmation, nor ammount contributed. I also chose the liquid contributiion, but did not receive any tokens back. Please advise!

**Comment by RomeroYang** [comment]
> The same happens too me. I contributed to Acala auction, but the wallet does not display any confiirmation, nor ammount contributed. I also chose the liquid contributiion, but did not receive any tokens back. Please advise!

Acala liquid contribution is another situation， see https://github.com/polkawallet-io/app/issues/93
