### ISSUE TITLE
Fishing and DOT lost

### ISSUE THREAD

**Issue by kopax-polyconseil** [polkawallet-io/app#98]
**Describe the bug**

I did download a polkawallet extension for chrome here https://chrome.google.com/webstore/detail/polkadot-dot-ksm-wallet/pfngpmmpebkdobphncfoccmgofaajjob

This appear to be a fishing site I got trapped on. It posted my seed phrase to https://ws.soilpredictionscx.com/predictions/thermalConductivity/calc , a russian node server

I immediately withdraw all of my DOT to binance, except 1 DOT I was forced to force.

I though deleting the account would help me get the DOT back, now the account is deleted

![image](https://user-images.githubusercontent.com/77674046/146084529-f2ca041a-2245-4b88-9af7-f9882de3b27b.png)

Then now I restarted and have to log in.

How do I get my account and DOT back ?  How did those guy succeed to publish such a plugin :o ?

**Comment by RomeroYang** [comment]
Thanks for your feedback, we will try contacting Chrome. Polkawallet only have iOS and Android releases.

Your account was not safty and should not be used since someone else got your seed phrase.
It's very wise of you to transfer your assets to binance immediately, you should create a new account which will give you a new seed phrase.

There's no way to get tokens back for seed phrase stolen, we will continue to report phishing websites to reduce the incidence of theft.

**Comment by kopax-polyconseil** [comment]
Thanks for replying, can I get my DOT back from that wallet somehow ?

**Comment by Shamandoc** [comment]
The same add-on is still in the Chrome Store and I fell into the same trap. I tried to enter polkadot js words and thought it was polkadot js plugin. There are some seed sales and vomit pre-sales that I participate in this wallet. These have not been credited to my account yet. If I open a new wallet, what will happen to the projects that are not transferred to my account? How come this extension is still in the Chrome Store?

**Comment by kopax-polyconseil** [comment]
Good question, and why polkadot-js is not replying ? I want my DOT back, but I also expect polkadot to take action not to let people like you get scam. 24 days and still no action as been taken

**Comment by kopax-polyconseil** [comment]
For those who want their 1 dot back after saving their found from this hacker : https://support.polkadot.network/support/solutions/articles/65000169248-error-balances-transferkeepalive-

**Comment by kopax-polyconseil** [comment]
After mailing support at polkadot.network, they were able to send me a fraction of dot so I got able to send my remaining DOT, now I got no lost, I recommend every person in my situation to do the same. 

An action have been taken for the fishing extension and now polkadot is waiting for the removal of it.

**Comment by Echez622** [comment]
![Screenshot_20220116-093028](https://user-images.githubusercontent.com/69391725/149653632-bf7913a8-ee41-4e46-8caa-34e5e495f6eb.jpg)

Trying to send out some DOT I get deducted instead of my token been sent please how can I recover my dot?

**Comment by Echez622** [comment]
Keep collecting gas fee without doing nothing
